name: flutflix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_ui_firestore: ^1.6.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  retrofit: ^4.1.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
