// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2osRXYPUTgBCasRN_tr5lvZksDeGtRSY',
    appId: '1:348203897162:web:2c06ec5546030755a3b1b3',
    messagingSenderId: '348203897162',
    projectId: 'flutflix-tutorial',
    authDomain: 'flutflix-tutorial.firebaseapp.com',
    storageBucket: 'flutflix-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxWlMT-HF2lkpLjA3I7wXDowZhGoGC1M',
    appId: '1:348203897162:android:1409fbaf5279eb25a3b1b3',
    messagingSenderId: '348203897162',
    projectId: 'flutflix-tutorial',
    storageBucket: 'flutflix-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoCpDD3CAobZBNCylQ9p7JRZvBdnXRZs',
    appId: '1:348203897162:ios:6ae4f344f02c2cc2a3b1b3',
    messagingSenderId: '348203897162',
    projectId: 'flutflix-tutorial',
    storageBucket: 'flutflix-tutorial.appspot.com',
    iosClientId: '348203897162-k60asik3f3rlq8t1s40l1fgi8edb2kr0.apps.googleusercontent.com',
    iosBundleId: 'com.hieutv.flutflix',
  );
}
